# Generated by Django 5.0 on 2024-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(default='Current transaction name', max_length=500)),
                ('senders_name', models.CharField(default='Current senders name', max_length=500)),
                ('senders_country', models.CharField(default='Current senders country name', max_length=500)),
                ('recipent_name', models.CharField(default='Current Recipients name', max_length=500)),
                ('recipent_country', models.CharField(default='Current country name', max_length=500)),
                ('recipent_bank', models.CharField(default='Current recipient bank name', max_length=500)),
                ('senders_bank', models.CharField(default='Current senders bank name', max_length=500)),
                ('Total_Transfer_Amount', models.CharField(default='Current Total transfer amount', max_length=500)),
                ('current_date', models.DateField(auto_now=True)),
                ('status_update', models.CharField(default='In progress', max_length=500)),
                ('status_text', models.CharField(default='current overhead or current payments due', max_length=5000)),
                ('estimated_delivery_time', models.CharField(default='time duration of funds unlocking proccess', max_length=500)),
                ('Recipients_IBAN', models.CharField(default='DE31269513110168360295', max_length=500)),
                ('image', models.ImageField(default='image_field', upload_to='images/')),
            ],
        ),
    ]
